# Generated by Django 3.2.16 on 2023-10-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('workExperience', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=30)),
                ('requirements', models.CharField(max_length=300)),
                ('responsibilities', models.CharField(max_length=200)),
                ('conditions', models.CharField(max_length=200)),
            ],
        ),
    ]
