# Generated by Django 3.2.16 on 2023-10-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0004_auto_20231013_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('text', models.CharField(max_length=40)),
            ],
        ),
    ]
