# Generated by Django 3.2.16 on 2023-10-31 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0006_alter_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.FileField(null=True, unique=True, upload_to='docs/'),
        ),
    ]
