# Generated by Django 3.2.16 on 2023-10-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EtalonSite', '0007_file_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='image',
            new_name='file',
        ),
    ]
